name: ci

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'manifest-files/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jitsi-custom:${{github.run_number}}


  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [docker]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install yq
        uses: mikefarah/yq@v4.15.1 

      # Debug
      - name: Debug-1
        run: |
          ls
          pwd
          ls ../

      - name: update infra yaml file
        run: |
          cd manifest-files
          yq e -i '.spec.template.spec.containers[2].image="${{ secrets.DOCKERHUB_USERNAME }}/jitsi-custom:${{github.run_number}}"' 030-deployment.yaml
          cat 030-deployment.yaml
      - name: push change
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: manifest-files/030-deployment.yaml
          destination_repo: Ajay-Chidambaram/jitsi-custom
          destination_branch: main
          destination_folder: manifest-files
          user_email: silambu.ajayk@gmail.com
          user_name: Ajay-Chidambaram
          commit_message: update image version ${{github.run_number}} in manifest yaml file